### ISSUE TITLE
Dataset is missing

### ISSUE THREAD

**Issue by JunsFu** [ando-hub/MSA_Pretrain#5]
![image](https://github.com/ando-hub/MSA_Pretrain/assets/100461491/fc37db50-c47a-4efa-bd11-6fdfb0171ba7)
Thank you for your hard work. 

I encountered some problems in training setup_cmumosi.sh. I couldn't find a way to obtain the relevant data sets：FileNotFoundError: [Errno 2] No such file or directory: './data/dataset/cmumosei/label/sentiment_regress/train.txt'
.
 Can you provide a link to the relevant data sets? Greatful!

**Comment by ando-hub** [comment]
Please confirm that you have manually downloaded the dataset and labeled it as `$cmumosi_root` and `$cmumosi_label_csd`. Note that automatic downloading (stage 0) is not functional due to the unavailability of the following download URLs. To obtain the original dataset, kindly contact the authors at CMU.
```
http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSI.zip
http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosi/seq_length_50/mosi_data_noalign.pkl
```

**Comment by HandsomeCBX** [comment]
> Please confirm that you have manually downloaded the dataset and labeled it as `$cmumosi_root` and `$cmumosi_label_csd`. Note that automatic downloading (stage 0) is not functional due to the unavailability of the following download URLs. To obtain the original dataset, kindly contact the authors at CMU.
> 
> ```
> http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSI.zip
> http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosi/seq_length_50/mosi_data_noalign.pkl
> ```

Thank you for your report,but there is a problem.It failed to connect.
![image](https://github.com/ando-hub/MSA_Pretrain/assets/148057185/bf4d2335-5a33-40b4-83ed-2cdb19d69baa)
